// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX24YJC0r7ein6uIAHp1O76byyy6d9RR8',
    appId: '1:989715065913:android:ed1a45d7343420ead2f1e8',
    messagingSenderId: '989715065913',
    projectId: 'pillbox-c37ee',
    databaseURL: 'https://pillbox-c37ee-default-rtdb.firebaseio.com',
    storageBucket: 'pillbox-c37ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9h0ER0ZFAsAfskXgNUI4vzsHPZhII54',
    appId: '1:989715065913:ios:4b383c8f13206055d2f1e8',
    messagingSenderId: '989715065913',
    projectId: 'pillbox-c37ee',
    databaseURL: 'https://pillbox-c37ee-default-rtdb.firebaseio.com',
    storageBucket: 'pillbox-c37ee.appspot.com',
    iosClientId: '989715065913-l0h419565vabfs1nqketp223cgq47j5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillbox',
  );
}
